### ISSUE TITLE
To do app using  the package

### ISSUE THREAD

**Issue by ccfiel** [ShadyBoukhary/flutter_clean_architecture#16]
We made a sample todo https://github.com/bailabs/todo base on your package. Did we do it correctly? any comments? @ShadyBoukhary  :)

**Comment by ShadyBoukhary** [comment]
Thanks for your interest in the package. Your example looks good. I do have a couple of notes though.

[Here](https://github.com/bailabs/todo/blob/master/lib/app/pages/home/home_view.dart#L44), instead of `callback: () => controller.retrieveData(),`, you can write `callback: controller.retrieveData,`. You don't need to create another function call.

In Domain, if your `UseCase` does not need to return any values _i.e._ it just completes some task, you should extend `CompletableUseCase` rather than `UseCase`. For example, [this usecase: complete_todo_usecase.dart](https://github.com/bailabs/todo/blob/master/lib/domain/usecases/complete_todo_usecase.dart) usecase should be a completable since it does not return any data. Using `CompletableUseCase` makes the code more concise and shorter. 

Also, you should always return an Observable with a stream in a usecase, even if it doesn't return data otherwise errors will not be reported in your usecase specified above. 

[Here](https://github.com/ShadyBoukhary/Axion-Technologies-HnH/blob/development/lib/domain/usecases/auth/logout_usecase.dart) is an example of a usecase that does not return any data.
```dart
  @override
  Future<Observable<User>> buildUseCaseObservable(void ignore) async {
    final StreamController<User> controller = StreamController();
    try {
      await _authenticationRepository.logout();
      controller.close();
    } catch (e) {
      _logger.shout('Could not logout the user.', e);
      controller.addError(e);
    }
    return Observable(controller.stream);
  }
```
Notice how this doesn't return any data yet it calls `controller.close()`. This triggers the `onComplete()` in the `Observer`. You typically want to handle errors as well. 

` return Observable(controller.stream);` this is a lot more concise than `return Future<Observable<List<Todo>>>.value(Observable(controller.stream));` in [this usecase](https://github.com/bailabs/todo/blob/master/lib/domain/usecases/get_all_todos_usecase.dart#L15), which should also extend `CompletableUseCase` rather than `UseCase`. That also goes for your edit and remove usecases as well.

Everything else looks good. Let me know if you have more questions.

Thanks,

Shady

**Comment by ccfiel** [comment]
Thank you!!! :)

**Comment by ccfiel** [comment]
@ShadyBoukhary we have made the modification https://github.com/bailabs/todo is this what you mean? :)

**Comment by ShadyBoukhary** [comment]
@ccfiel Yes! Looks good now!

**Comment by ccfiel** [comment]
wow! @ShadyBoukhary ! :) thank you very much for your package! :+1:

**Comment by ShadyBoukhary** [comment]
@ccfiel Have you considered pushing your example to https://github.com/brianegan/flutter_architecture_samples ? This might be helpful as this repository maintains a collection of different Flutter architectural samples. Your ToDo app would be fitting there.

**Comment by ccfiel** [comment]
@ShadyBoukhary I will submit this to them :)
