### ISSUE TITLE
Extending an base usecase, complexity vs consistency

### ISSUE THREAD

**Issue by cosinus84** [ShadyBoukhary/flutter_clean_architecture#37]
Because you became a source of inspiration :), I looked over you code from https://github.com/ShadyBoukhary/Axion-Technologies-HnH (development branch) and I saw that you don't extends a base use case. Do you think is really necessary to extend a base usecase witch adds more complexity? For returning a bool to have to involve streams? (like in login case) https://github.com/ShadyBoukhary/flutter_clean_architecture/issues/3#issuecomment-489761346

---
On another examples out there I saw something done with dartz package, Also to much, I don;t always want to return a future and what about **Type** being a stream??? 

```
abstract class UseCase<Type, Params> {
  Future<Either<Failure, Type>> call(Params params);
}

```
---
Also creating more abstract usecases classes looks a bit silly. 
Because dart classes are already interfaces we can use this in testing and avoid using a base usecase and use **stream base use case** when we are dealing with streams. 
Can you explain a bit about this motivation on using this base usecase everywhere?

Thanks!

**Comment by ShadyBoukhary** [comment]
Hi @cosinus84,

>I looked over you code from https://github.com/ShadyBoukhary/Axion-Technologies-HnH (development branch) and I saw that you don't extends a base use case.

The code there does extend a base usecase. The base usecase is provided by the package just like `Controller` class.

>Do you think is really necessary to extend a base usecase witch adds more complexity? For returning a bool to have to involve streams? (like in login case)

I realize that there are occasions where using stream is an overkill. This is something I've been thinking about in order to reduce the complexity of the package. In the future, i want to do some internal restructuring and provide more options that allow users to choose the level of complexity of their code. For example, that would include a type of usecase that doesn't involve streams.

>On another examples out there I saw something done with dartz package, Also to much, I don;t always want to return a future and what about Type being a stream???

Usecases are meant for mostly asynchronous operations, which is why they return a `Future`. The type is a stream because the `Presenter` is listening to the result using an `Observer`. Notice how in the examples the results are packaged into a stream controller.

>Also creating more abstract usecases classes looks a bit silly.

You are not creating abstract usecases. These usecases are concrete and are instantiated inside the presenter. The only abstract usecases present are the ones already provided by the package. You do not need to create any abstract usecases.

>Because dart classes are already interfaces we can use this in testing and avoid using a base usecase and use stream base use case when we are dealing with streams.

The architecture is not difficult to use in testing as all the dependencies can be easily mocked. I have noted earlier that I would like to update the package to allow for lesser complexity if the user chooses to. Until then, feel free to either follow the examples of the package or bypass it as you see fit.

**Comment by cosinus84** [comment]
Hello, before we close this can you add something about validation in documentation or example. After some digging and 1000 browser tabs, I resumed that each layer need to add some validation. For example the presentation(view) can add a validation a field value being only numeric. When we build the Request object to send to usecase, the Request has the amount field type as double. In the use case the validation is that the amount should be grater then 0.

Thanks, again :)

**Comment by ShadyBoukhary** [comment]
If you're talking about validating user input data, then that should be done in the presentation layer. You can enforce type-safety by simply using explicit types instead of `dynamic`.

**Comment by cosinus84** [comment]
Right, so there we have presentation user input data validation, and then in the use case the business logic validation of the request (or some domain service for validation that is needed for more  usecases)

**Comment by ShadyBoukhary** [comment]
Yes, depending on the usecase, there might be some validation there. However, this is the responsibility of the user of the package to add as different usecases would have different requirements.
