### ISSUE TITLE
Web support?

### ISSUE THREAD

**Issue by limcheekin** [ShadyBoukhary/flutter_clean_architecture#61]
Thanks for published the owesome flutter package, I find out from https://pub.dev/packages/flutter_clean_architecture that it is not support "Web" yet. May I know anything blocking it to support flutter web?

**Comment by rafaelcmm** [comment]
Hi @limcheekin!

Yes, `flutter_clean_architecture` works plenty on web! I have some web projects myself!

This is probably some documentation issue that can be easily fix on `pubspec.yaml`.

Feel free to submit a pull request fixing it, we would love it!

If you can't I will happily fix it as soon as I can.

Thanks for let us know!

**Comment by limcheekin** [comment]
thanks for confirmation. I not sure how to fix it.

**Comment by rafaelcmm** [comment]
@limcheekin You can use this package on web as you like.

Although, the only thing that will not work on web is `BackgroundUseCase` feature, since dart:isolate is not supported on web.

All the other features are working, so you are good to go if you don't need this.

I'm working on a `null safety` version, and as long as flutter is updating, maybe we find a way to support something like isolate on web.

Thanks! Hope it helps.

I'm closing this issue, please feel free to reopen if you need.
